---
# defaults file for cake

project_name: cake
server_access_key_name: cake_key
server_count: 1
server_instance_type: t2.medium
server_ami_name: ami-a192bad2
server_region: eu-west-1
ec2_vpc_subnet_id: subnet-a69beed0
ec2_monitoring: yes
server_state: present
server_env: dev
cake_services: 
  - name: cake-app
    app: cake
    owner: cake


elb_state: present
elb_region: "{{ server_region }}"
elb_subnets: "{{ ec2_vpc_subnet_id }}"
elb_con_draining: 60
elb_idletimeout: 300
elb_cross_az_lb: yes
